- name: CDPYME restart mon pre
  hosts: all
  enviroment:
    http_proxy: z928258:H7a2kcz1@prxmxnvprbmx.mx.corp:8015
    https_proxy: z928258:H7a2kcz1@prxmxnvprbmx.mx.corp:8015
  tasks:
    - name: CDPYME restart mon pre
      debug:
        msg: "All pods are OK"
